site_name: JME-Docs
site_url: https://ramimanaf.github.io/JMolecularEnergy/
site_description: JMolecular Energy Documentation.

repo_url: https://github.com/RamiManaf/JMolecularEnergy/
edit_uri: tree/pages/src/JME-Docs/docs

nav:
    - 'Getting Started': index.md
    - 'Force Field': forcefield.md
    - 'MMFF94 Force Field': mmff94.md
    - 'Calculate Potential Energy without 3D Coordinates': calculate-energy-without-coordinates.md
    - 'Energy Minimization': energy-minimization.md
    - 'Constraints': constraint.md
theme: 
  name: readthedocs
  user_color_mode_toggle: true
  logo: img/logo.png
